services:
  perfma-gpt:
    image: my-image-0
    container_name: my-server
    environment:
      - JIMAO=1
    ports:
      - "9091:9091"
      - "8091:8091"
    volumes:
      - /Users/jimao/github/my-docker-nodejs:/root/server
    command: node ./index.js
    restart: unless-stopped
