services:
  perfma-gpt:
    image: my-image-0
    container_name: my-server
    environment:
      - JIMAO=1
    ports:
      - "42800-42900:42800-42900"
    volumes:
      - ./:/root/server
    command: node ./index.js
    restart: unless-stopped
